# Configuration for cbprocess preprocessing pipeline.
# This pipline:
#  - selects MC/data parquet files
#  - reads parquet in batches
#  - applies TA-style quality cuts
#  - computes reconstructed and thrown energies
#  - saves CSVs and filtered Parquet files


 array:
   # Choose between:
   #   "TASD" - full Telescope Array surface detector
   #   "CBSD" - checkerboarded Telescope Array surface detector (every-other detector)
   type: "TASD" # or "CBSD"

 data:
   # Parquet file paths for MC and data
   # TASD files
   tasd:
    mc_file: "data/tlfptn_1850.all.tlsdfit.result.parquet"
    dt_file: "data/sddt.main.result.parquet"

   # CBSD files
   cbsd:
    mc_file: "data/tlfptn_1850.tlsdfit.result.parquet"
    dt_file: "data/sddt.cb.noCuts.result.parquet"

 processing:
  # Number of time periods ot split the data into:
  #   1 → no splitting (all 16 years)
  #   2 → first 8 years / last 8 years
  #   3 → thirds
  #   N → general case
  periods: 1

 quality_cuts:
  number_of_good_sd: 5
  theta_deg: 45.
  boarder_dist_m: 1200.
  geometry_chi2: 4.
  ldf_chi2: 4.
  ped_error: 5.
  frac_s800: 0.25

 output:
  base_dir: "output"
  plots_dir: "output/plots"
  logs_dir: "output/logs"
  runs_dir: "output/runs"